#!/usr/bin/sh

## Copy selected wallpaper and set it using xwallpaper ##

while read file
do
  fullpath="$(pwd)/$file"
  case "$1" in
  "w")
        cp "$file" ~/.config/nsxiv/wall &&
        xwallpaper --zoom "$HOME/.config/nsxiv/wall"
    esac
done
