#!/usr/bin/sh

## Autostart Script ##
$HOME/.config/bspwm/autoload/startup/autostart

## Workspaces ##
bspc monitor -d '' '' '' '' '' '' '' '' ' '

## General Settings ##
bspc config border_width 1
bspc config split_ratio 0.46
bspc config window_gap 6
bspc config right_padding 1
bspc config left_padding 1
bspc config bottom_padding 1

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config normal_border_color "#2F3D44"
bspc config focused_border_color "#969696"

## Rule Set ##
bspc rule -a File Transfer* state=floating
bspc rule -a Save file state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a mpv state=floating
bspc rule -a Lxappearance state=floating
# bspc rule -a Transmission-gtk state=floating
# bspc rule -a KeePassXC state=floating
